POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "account": "hihihi",
    "password": "123456fds",
    "summoner": "혼모노",
    "imageUrl": "./images/defaultUser.png",
    "encryptedId": "g8_gAvyoh-x35TeclWkFXJP5abc9XKJW5JcBQIHg4avMsSEA"
}

# ###
# POST http://localhost:3000/api/user/checkid
# Content-Type: application/json

# {
#     "account": "won"
# }


# ###

# GET http://localhost:3000/

###

POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "account": "jeongmin",
    "password": "11111111"
}
