POST http://localhost:3000/user/register
Content-Type: application/json

{
    "userid": "hihihi",
    "password": "123456",
    "summoner": "혼모노",
    "imageUrl": "./images/defaultUser.png",
    "encryptedId": "g8_gAvyoh-x35TeclWkFXJP5abc9XKJW5JcBQIHg4avMsSEA"
}


###

GET http://localhost:3000/